{% set version = "5.6.0" %}
{% set short_version = ".".join(version.split(".")[:2]) %}

package:
  name: qt5
  version: {{ version }}

source:
  fn:   qt-everywhere-opensource-src-{{ version }}.tar.xz                                                              # [unix]
  url:  http://download.qt.io/official_releases/qt/{{ short_version }}/{{ version }}/single/qt-everywhere-opensource-src-{{ version }}.tar.xz  # [unix]
  sha256:  76a95cf6c1503290f75a641aa25079cd0c5a8fcd7cff07ddebff80a955b07de7                                            # [unix]
  fn:   qt-everywhere-opensource-src-{{ version }}.zip                                                                 # [win]
  url:  http://download.qt.io/official_releases/qt/{{ short_version }}/{{ version }}/single/qt-everywhere-opensource-src-{{ version }}.zip     # [win]
  sha256:  949ec2eebefe7e4a3580082d2d700e48713102bc017e640ed77a076cdbcce1f9                                            # [win]

build:
  detect_binary_files_with_prefix: true
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]

requirements:
  build:
    - 7za                    # [win]
    - curl
    - bison                  # [linux]
    - m2-bison               # [win]
    - flex                   # [linux]
    - fontconfig             # [linux]
    - freetype               # [unix]
    - gst-plugins-base       # [linux]
    - icu
    - jom                    # [win]
    - jpeg
    - libpng        1.6*
    - libxcb                 # [linux]
    - openssl
    - perl       >=5.20
    - python
    - zlib
    - m2-gperf   # [win]
    - m2-bison   # [win]
    - m2-flex    # [win]

  run:
    - freetype               # [unix]
    - jpeg
    - icu
    - libpng        1.6*
    - libxcb                 # [linux]
    - fontconfig             # [linux]
    - openssl
    - gst-plugins-base       # [linux]
    - zlib

about:
    home: http://www.qt.io
    license: LGPLv3
    summary: GUI application development framework

extra:
    recipe-maintainers:
        - ccordoba12
        - ddale
        - jdreaver
        - msarahan